### ISSUE TITLE
[FEAT] 회원가입 UI 구현

### ISSUE THREAD

**Issue by dangsal** [DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple#11]
## 💡 Issue

- 애플 로그인은 제외하겠습니다. 
- 닉네임 입력 뷰 UI 구현하겠습니다.

## 📝  Todo
- [ ] todo !
- [x] 닉네임 뷰 라벨 
- [x] 텍스트필드
- [x] 텍스트필드 제한
- [x] 키보드 위치 애니메이션
- [x] 메인버튼 
- [x] 메인버튼 활성화 비활성화
- [x] 텍스트 필드 컴포넌트화하기

**Comment by MMMIIIN** [comment]
아자아자 화이팅 !
