### ISSUE TITLE
[FEAT] MyReflectionFeedback으로 데이터 넘기기

### ISSUE THREAD

**Issue by dangsal** [DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple#155]
## 💡 Issue

앞에서 Detail 뷰에서 받은 데이터를 MyReflectionFeedback뷰로 넘기는 작업을 하겠습니다.
## 📝  Todo
- [ ] todo !
- [ ] MyReflectionFeedback 에 넘길 데이터 만들기
- [ ] MyReflectionFeedback 로 넘긴 데이터 연결하기
- [ ] MyReflectionFeedback 에서 받은 데이터 뷰에 뿌려주기
