### ISSUE TITLE
[CHORE] JoinTeamVC에서 발생한 버그(수정사항)들 반영하기

### ISSUE THREAD

**Issue by Guel-git** [DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple#244]
## 💡 Issue
JoinTeamViewController과 관련된 백로그 사항들을 반영합니다.

## 📝  Todo
- [x] 잘못된 초대코드 입력했을 경우 Alert 띄우기
https://www.notion.so/Alert-6ccf9ee2683e44a9bca89c33bdb1444b
- [x] 영문/대문자를 디폴트 키보드 상태로 설정하기
https://www.notion.so/75ad2851b35d4752afaff02879ca0f63
- [x] TextField에 border 추가하기
https://www.notion.so/TextField-border-06b25ae6f9ca4a99b15c9c5c67a7e8b6
