### ISSUE TITLE
[CHORE] 피그마와 다른 UI/색 수정하기 , 멤버가 5명 이상 되는 경우 멤버 최하단 CollectionViewCell 이 가려지는 버그 해결하기

### ISSUE THREAD

**Issue by dangsal** [DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple#262]
## 💡 Issue

![스크린샷 2023-01-07 오후 4 55 03](https://user-images.githubusercontent.com/59243274/211140298-6b0a2805-30f0-4b36-ba12-07fa145c19e3.png)
![스크린샷 2023-01-07 오후 11 42 20](https://user-images.githubusercontent.com/59243274/211156304-0f71d8fd-84fb-4cbc-8fc7-43b2ce9d58a8.png)

## 📝  Todo
- [x] todo !
- [x] MemberCollectionViewCell 색 white100으로
- [x] 피드백 멤버 & 종류 Container 색 → white200으로
- [x] 피드백 멤버 컬렉션 뷰 셀 높이 조정
- [x] 멤버가 5명 이상 되는 경우 멤버 최하단 CollectionViewCell 이 가려지는 버그 해결하기
