### ISSUE TITLE
[ADD] SetNickname 바뀐 UI 구현

### ISSUE THREAD

**Issue by Guel-git** [DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple#278]
## 💡 Issue
|<img src="https://user-images.githubusercontent.com/81340603/213848545-f063707b-a30f-49ee-ae96-31dc1e5e23c5.png" width=180px />|<img src="https://user-images.githubusercontent.com/81340603/213848547-231199d2-9fd4-49b2-9099-99dedeaa13c6.png" width=180px />|
|:---:|:---:|
|<center>기본</center>|<center>키보드 올라올 경우</center>|

## 📝  Todo
- [x] Navigation Bar
- [x] 프로필 사진 button 추가
- [x] TextField Label 추가
- [x] 역할 TextField 추가
- [x] 키보드 올라왔을 때 > TitleLabel을 navbar title로 / 남은 컴포넌트들 전체적으로 이동
- [x] 키보드 내려갔을 때 원상복귀
