### ISSUE TITLE
[ADD] 건너뛰기 시 보이는 HomeVC

### ISSUE THREAD

**Issue by seongmin221** [DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple#297]
## 💡 Issue

이전 회의에서 처음 가입할 때 팀에 꼭 합류할 필요 없이 `건너뛰기` 기능을 넣기로 했습니다
그렇게 HomeVC 에 도착했을 때 보일 View에 대한 이슈입니다

## 📝  Todo
- [ ] preview 상태일 때 JoinReflectionButton UI 변경
- [ ] preview 상태일 때 JoinReflectionButton action 변경
- [ ] teamButton UI 변경
