### ISSUE TITLE
[ADD] Setup navigation 순서 변경 & 초대코드 공유하기 기능 구현

### ISSUE THREAD

**Issue by Guel-git** [DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple#300]
## 💡 Issue
1. Setup navigation 순서 변경 하기 
(기존) Login > SetNickname > JoinTeam > ( CreateTeam > InvitationCode )
(변경) Login > JoinTeam > ( CreateTeam ) > SetNickname > InvitationCode

2. 초대코드 공유하기 기능 구현

## 📝  Todo
- [x] getCertainTeamName api
- [x] userJoinTeam api
- [x] createTeam api
- [x] Login > JoinTeam > SetNickname > InvitationCode
- [x] JoinTeam > CreateTeam > SetNickname
- [ ] 이미지 data api 연결
- [x] teamId 있을 경우: SetNicknameVC로
- [x] teamId & userId 있을 경우: rootview를 CustomTabBarViewController
- [x] 초대코드 공유하기 기능 구현
