### ISSUE TITLE
[CHORE] From To 순서 변경, 텍스트 필드 입력 후 버튼이 눌릴 수 있도록 변경

### ISSUE THREAD

**Issue by dangsal** [DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple#57]
## 💡 Issue

1) 현재 피드백 줄 사람을 입력해주세요 뷰에서 From 이 To 보다 먼저나오는것이 순서상 맞지 않다고 생각합니다.
저희 편지를 쓸때를 예로 들면, 진저에게, 호야가 순서로 To, From 순서 입니다. 자연스럽고 이미 유저 경험이 많이 쌓인 저 순서가 좋을 거 같다고 판단했습니다.
![IMG_5751](https://user-images.githubusercontent.com/59243274/198182585-16c93ce8-8172-4798-b805-d13794467b2d.PNG)

2) 현재 뷰에서는 텍스트필드가 올라와 있을때 버튼이 눌리지 않고 그 뒤에 있는 뷰가 눌리게 됩니다. 그래서 Start제안하기 부분의 버튼을 누르면 제안하기 토글이 터치되는 현상이 있습니다. 변경하도록 하겠습니다.

![IMG_5750](https://user-images.githubusercontent.com/59243274/198182600-db489259-d281-47ad-812b-e088ee89e629.PNG)

## 📝  Todo
- [ ] todo !
- [ ] From,To 순서 변경
- [ ] 버튼 클릭 가능하도록
- [ ] 완료 누를시 액션 추가 되도록
