### ISSUE TITLE
[ADD] 보관함 탭 View 추가

### ISSUE THREAD

**Issue by MMMIIIN** [DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple#65]
## 💡 Issue

<img width="296" alt="image" src="https://user-images.githubusercontent.com/78677571/199428493-a6ae70b3-6caf-4576-b93c-6c010f843715.png">
테스트 플라이트로 미루어졌던 뷰를 생성합니다.

## 📝  Todo
- [x] 타이틀 Label과 좌우 CollectionView 생성 PR
- [x] Continue, Stop CollectionView 생성 PR
- [ ] Feedback CollectionView의 divider 추가 PR
