### ISSUE TITLE
[ADD] Alert View 구현

### ISSUE THREAD

**Issue by Guel-git** [DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple#77]
## 💡 Issue
FeedbackFromMeDetailView 와 호야가 만들었던 팀 합류 뷰에서 사용되는 Custom Alert 을 Global UIComponent 로 넣을 예정입니다!
|<img src="https://user-images.githubusercontent.com/81340603/200157415-b5b2f146-c720-47d4-a24e-6b41e070c54b.png" />|<img src="https://user-images.githubusercontent.com/81340603/200157417-a25111f4-0a3e-492f-a5db-feadd0fc4200.png" />|

## 📝  Todo
- [ ] 파일 & 디렉토리 생성
- [ ] enum 생성 - join, cancel
- [ ] Background View
- [ ] Alert View
- [ ] Title & Subtitle label
- [ ] Button 두 개
- [ ] Divider
- [ ] setAttribute 함수 생성
- [ ] FeedbackFromMeDetail 에 컴포넌트 올리기
- [ ] isHidden 처리
- [ ] button action 추가
