### ISSUE TITLE
[FIX] 자잘한 버그 수정

### ISSUE THREAD

**Issue by dangsal** [DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple#97]
## 💡 Issue

현재 코드에는 반영되지 못한 자잘한 버그가 있습니다. 그 버그들을 찾고 수정하는 작업입니다.

## 📝  Todo
- [ ] todo !
- [ ] 키보드 올라올때 button위로 올리는 애니메이션 추가
- [x] 초대코드 복사 기능
- [ ] 잘못된 코드 핸들링
- [x] 버튼을 제외한 영역 터치시 button 내리기
- [x] 버튼 내릴때 팀 생성하기라벨 뷰 히든 처리
- [x] labelButtonView 버튼에 subButton 색 적용
- [ ] 그 외 코드 버그 찾기 (찾고 고치기)
